clusterInstance: "onprem-prod-1"

appsDomain: "apps.hc03.homelab.ticq.org"

tenants:
  team-backend:
    enableTenantNamespaceAutoProvisioning: "true"
    tenantProvisionedRepository: "https://github.com/GijsvanDulmen/openshift-gitops-tenants-setup"
    tenantProvisionedBranch: "main"
  team-frontend: {}

tenantGitopsInstances: 2

enableDisconnected: "false"
